# Generated by Django 4.2.9 on 2024-02-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('text', models.TextField()),
                ('arq', models.FileField(upload_to='imagens')),
            ],
        ),
    ]
